export enum Validation {
  EMPTY_VALUE = "EMPTY_VALUE",
  NOT_WITHIN_RANGE = "NOT_WITHIN_RANGE",
  IS_NOT_POSITIVE_NUMBER = "IS_NOT_POSITIVE_NUMBER",

  INVALID_VALUE = "INVALID_VALUE",
  INVALID_DATA = "INVALID_DATA",
}
