export enum Validation {
  EMPTY_VALUE = "EMPTY_VALUE",
  NOT_WITHIN_RANGE = "NOT_WITHIN_RANGE",
  LARGER_THAN_MAX_NUMBER = "LARGER_THAN_MAX_NUMBER",
  LESS_THAN_MIN_NUMBER = "LESS_THAN_MIN_NUMBER",
  IS_NOT_POSITIVE_NUMBER = "IS_NOT_POSITIVE_NUMBER",

  INVALID_VALUE = "INVALID_VALUE",
  INVALID_DATA = "INVALID_DATA",
}
